spring:
  application:
    name: ms-auth
  datasource:
    url: jdbc:mariadb://${MYSQLHOST}:${MYSQLPORT}/${MYSQLDATABASE}?useSSL=false&allowPublicKeyRetrieval=true&serverTimezone=UTC
    username: ${MYSQLUSER}
    password: ${MYSQLPASSWORD}
    driver-class-name: org.mariadb.jdbc.Driver
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: ${JPA_SHOW_SQL:true}
    properties:
      hibernate:
        format:
          sql: true
        dialect: org.hibernate.dialect.MySQLDialect

server:
  port: ${PORT:${SERVER_PORT:8080}}

springdoc:
  api-docs:
    enabled: true
  swagger-ui:
    enabled: true
    path: /swagger-ui.html

eureka:
  client:
    enabled: false
    register-with-eureka: false
    fetch-registry: false
    service-url:
      defaultZone: ${EUREKA_URI:http://localhost:8761/eureka/}
  instance:
    prefer-ip-address: true

jwt:
  secret: ${JWT_SECRET:wzO3r4PadzwqMhgV7h3GgvIrkopVoaIj3GvNZb7M3x4=}
  expiration-ms: ${JWT_EXPIRATION_MS:3600000}

bootstrap:
  admin:
    username: ${BOOTSTRAP_ADMIN_USERNAME:admin}
    password: ${BOOTSTRAP_ADMIN_PASSWORD:admin}
